//
// CandleRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CandleRequest: Codable {

    /** Name of the currency pair */
    public var baseTradingSymbol: String?
    /** Name of the exchange */
    public var exchange: String?
    /** Name of the market */
    public var interval: String?
    /** Name of the data format availables (standard) */
    public var quoteTradingSymbol: String?

    public init(baseTradingSymbol: String?, exchange: String?, interval: String?, quoteTradingSymbol: String?) {
        self.baseTradingSymbol = baseTradingSymbol
        self.exchange = exchange
        self.interval = interval
        self.quoteTradingSymbol = quoteTradingSymbol
    }

    public enum CodingKeys: String, CodingKey { 
        case baseTradingSymbol = "base_trading_symbol"
        case exchange
        case interval
        case quoteTradingSymbol = "quote_trading_symbol"
    }


}

