//
// ExchangeAssetsResponseInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExchangeAssetsResponseInner: Codable {

    /** Highest price of the time frame with two decimal points */
    public var name: String?
    /** Percetange change in the last 24 hours */
    public var _id: Double?
    /** Volume of currency exchanged in the time frame with two decimal points */
    public var tradinSym: String?
    /** Volume of currency exchanged in the time frame with two decimal points */
    public var symbol: String?

    public init(name: String?, _id: Double?, tradinSym: String?, symbol: String?) {
        self.name = name
        self._id = _id
        self.tradinSym = tradinSym
        self.symbol = symbol
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _id = "id"
        case tradinSym
        case symbol
    }


}

