//
// Exchange.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Exchange: Codable {

    /** Name of the digital asset exchange to get data from */
    public var exchange: String?

    public init(exchange: String?) {
        self.exchange = exchange
    }


}

