//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    public var code: Int?
    public var message: String?
    public var fields: String?

    public init(code: Int?, message: String?, fields: String?) {
        self.code = code
        self.message = message
        self.fields = fields
    }


}

