//
// OHCLV.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OHCLV: Codable {

    /** Closing price quote of the time frame with two decimal points */
    public var close: Float?
    /** Highest price of the time frame with two decimal points */
    public var high: Float?
    /** End date in YYYY/MM/DD */
    public var endDate: Date?
    /** Opening price quote of the time frame with two decimal points */
    public var _open: Float?
    /** Timestamp of the beggining of the frame */
    public var time: Date?
    /** Volume of currency exchanged in the time frame with two decimal points */
    public var volume: Float?
    /** Volume of currency exchanged in dollars the time frame with two decimal points */
    public var usdVolume: Float?
    /** Volume of currency exchanged in dollars the time frame with two decimal points */
    public var btcVolume: Float?
    /** Volume of currency exchanged in dollars the time frame with two decimal points */
    public var quoteVolume: Float?

    public init(close: Float?, high: Float?, endDate: Date?, _open: Float?, time: Date?, volume: Float?, usdVolume: Float?, btcVolume: Float?, quoteVolume: Float?) {
        self.close = close
        self.high = high
        self.endDate = endDate
        self._open = _open
        self.time = time
        self.volume = volume
        self.usdVolume = usdVolume
        self.btcVolume = btcVolume
        self.quoteVolume = quoteVolume
    }

    public enum CodingKeys: String, CodingKey { 
        case close
        case high
        case endDate = "end_date"
        case _open = "open"
        case time
        case volume
        case usdVolume
        case btcVolume
        case quoteVolume
    }


}

