//
// OrderbookRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OrderbookRequest: Codable {

    /** Name of the currency pair */
    public var baseTradingSymbol: String?
    /** Name of the exchange */
    public var exchange: String?
    /** Limit depth to extract from the orderbook */
    public var limit: Double?
    /** Name of the data format availables (standard) */
    public var quoteTradingSymbol: String?

    public init(baseTradingSymbol: String?, exchange: String?, limit: Double?, quoteTradingSymbol: String?) {
        self.baseTradingSymbol = baseTradingSymbol
        self.exchange = exchange
        self.limit = limit
        self.quoteTradingSymbol = quoteTradingSymbol
    }

    public enum CodingKeys: String, CodingKey { 
        case baseTradingSymbol = "base_trading_symbol"
        case exchange
        case limit
        case quoteTradingSymbol = "quote_trading_symbol"
    }


}

