//
// Text.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The text object takes any string of text. */

public struct Text: Codable {

    /** String of text or document to be analyzed */
    public var text: String?

    public init(text: String?) {
        self.text = text
    }


}

