//
// TickerResponseInner.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TickerResponseInner: Codable {

    /** Closing price quote of the time frame with two decimal points */
    public var lastUpdated: Date?
    /** Highest price of the time frame with two decimal points */
    public var name: String?
    /** Percetange change in the last 24 hours */
    public var percentChange24hUsd: Float?
    /** Opening price quote of the time frame with two decimal points */
    public var priceBtc: Float?
    /** Timestamp of the beggining of the frame */
    public var priceUsd: Float?
    /** Volume of currency exchanged in the time frame with two decimal points */
    public var symbol: String?

    public init(lastUpdated: Date?, name: String?, percentChange24hUsd: Float?, priceBtc: Float?, priceUsd: Float?, symbol: String?) {
        self.lastUpdated = lastUpdated
        self.name = name
        self.percentChange24hUsd = percentChange24hUsd
        self.priceBtc = priceBtc
        self.priceUsd = priceUsd
        self.symbol = symbol
    }


}

